/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ATVITunesTouchRemoteManager <NSObject>
-(id)pairedTouchRemotes;
-(id)pairableTouchRemotes;
-(BOOL)removePairedTouchRemote:(id)remote;
-(void)pairWithTouchRemote:(id)touchRemote withPIN:(id)pin;
-(unsigned long)sendGeneralPurposeMessage:(id)message;
@end

