/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BRDownload <NSObject>
-(int)downloadState;
-(int)qualifiedDownloadState;
-(int)downloadStateContext;
-(unsigned long long)expectedSize;
-(unsigned long long)byteCount;
-(double)timeUntilPlayable;
-(void)setPlayable:(BOOL)playable;
-(void)pause;
-(void)resume;
-(BOOL)testContent;
@end

