/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BRITunesUtilities <NSObject>
-(BOOL)attemptAuthorizationForAsset:(id)asset error:(id*)error;
-(void)deauthorizeAssetIfNecessary:(id)necessary;
-(id)iTunesCompareAscending:(BOOL)ascending withKey:(id)key;
-(id)sortStringForString:(id)string;
-(int)iTunesCompareString:(id)string toString:(id)string2;
-(id)urlSuitableForPlayback:(id)playback;
-(unsigned long)randomPlaylistIndex:(unsigned long)index;
-(id)keyBagPathForPairingGUID:(unsigned long long)pairingGUID;
-(id)rentalGUID;
@end

