/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRMediaObject.h"


@protocol BRMediaCollection <BRMediaObject>
-(id)provider;
-(id)collectionID;
-(id)title;
-(id)titleForSorting;
-(id)titleNoDefault;
-(id)titleForSortingNoDefault;
-(id)artist;
-(id)artistForSorting;
-(int)count;
-(id)mediaType;
-(id)mediaTypes;
-(id)mediaAssets;
-(id)assetEnumerator;
-(BOOL)isCompilation;
-(BOOL)isSingleArtistCompilation;
-(id)imageProxy;
-(id)collectionType;
-(id)parentCollection;
-(id)childCollections;
-(long)duration;
-(BOOL)isLocal;
-(BOOL)isAvailable;
-(BOOL)isHidden;
-(void)willBeDeleted;
-(id)date;
@end

