/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRMediaObject.h"


@protocol BRMediaAsset <BRMediaObject>
-(id)provider;
-(id)assetID;
-(id)title;
-(id)titleForSorting;
-(id)artist;
-(id)artistForSorting;
-(id)mediaSummary;
-(id)mediaDescription;
-(id)publisher;
-(id)composer;
-(id)composerForSorting;
-(id)copyright;
-(float)userStarRating;
-(void)setUserStarRating:(float)rating;
-(float)starRating;
-(id)rating;
-(BOOL)isHD;
-(BOOL)isWidescreen;
-(BOOL)closedCaptioned;
-(BOOL)dolbyDigital;
-(long)performanceCount;
-(void)incrementPerformanceCount;
-(void)incrementPerformanceOrSkipCount:(unsigned)count;
-(BOOL)hasBeenPlayed;
-(void)setHasBeenPlayed:(BOOL)played;
-(long)duration;
-(id)mediaURL;
-(id)previewURL;
-(id)trickPlayURL;
-(id)imageProxy;
-(id)imageProxyWithBookMarkTimeInMS:(unsigned)ms;
-(BOOL)hasCoverArt;
-(BOOL)isProtectedContent;
-(id)playbackRightsOwner;
-(id)mediaType;
-(BOOL)hasVideoContent;
-(BOOL)isDisabled;
-(id)collections;
-(id)primaryCollection;
-(id)artistCollection;
-(id)primaryCollectionTitle;
-(id)primaryCollectionTitleForSorting;
-(int)primaryCollectionOrder;
-(int)physicalMediaID;
-(id)seriesName;
-(id)seriesNameForSorting;
-(id)broadcaster;
-(id)episodeNumber;
-(unsigned)season;
-(unsigned)episode;
-(id)genres;
-(id)primaryGenre;
-(id)cast;
-(id)producers;
-(id)directors;
-(id)dateAcquired;
-(id)dateAcquiredString;
-(id)dateCreated;
-(id)dateCreatedString;
-(id)datePublished;
-(id)datePublishedString;
-(void)setBookmarkTimeInMS:(unsigned)ms;
-(void)setBookmarkTimeInSeconds:(unsigned)seconds;
-(unsigned)bookmarkTimeInMS;
-(unsigned)bookmarkTimeInSeconds;
-(unsigned)startTimeInMS;
-(unsigned)startTimeInSeconds;
-(unsigned)stopTimeInMS;
-(unsigned)stopTimeInSeconds;
-(id)lastPlayed;
-(void)setLastPlayed:(id)played;
-(id)resolution;
-(BOOL)canBePlayedInShuffle;
-(BOOL)isLocal;
-(BOOL)isAvailable;
-(void)skip;
-(id)authorName;
-(id)keywords;
-(id)viewCount;
-(id)category;
-(BOOL)isInappropriate;
-(int)grFormat;
-(void)willBeDeleted;
-(void)preparePlaybackContext;
-(void)cleanUpPlaybackContext;
-(long)parentalControlRatingSystemID;
-(long)parentalControlRatingRank;
-(BOOL)isExplicit;
-(BOOL)playable;
-(id)playbackMetadata;
-(void*)createMovieWithProperties:(void*)properties count:(long)count;
-(BOOL)isCheckedOut;
-(id)sourceID;
-(BOOL)isPlaying;
-(BOOL)isPlayingOrPaused;
@end

