/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct __ATVMediaItem* ATVMediaItemRef;

typedef struct _NSZone NSZone;

typedef struct __CFData* CFDataRef;

typedef struct __ATVDataServer* ATVDataServerRef;

typedef struct CGSize {
	float _field1;
	float _field2;
} CGSize;

typedef struct CGImage* CGImageRef;

typedef struct __IOSurface* IOSurfaceRef;

typedef struct CGPoint {
	float _field1;
	float _field2;
} CGPoint;

typedef struct AppContext AppContext;

typedef struct DLinkElement {
	struct DLinkElement* next;
	struct DLinkElement* prev;
} DLinkElement;

typedef struct JRFileSpecFunctionTable* JRFileSpecFunctionTableRef;
typedef struct JRFileSpec {
	unsigned kind;
	unsigned short flagsPrivate;
	unsigned volumeKindPrivate;
	JRFileSpecFunctionTableRef procs;
	union {
		struct {
			BOOL fullPathPrivate[1024];
			int volumeIDPrivate;
		} posix;
	} u;
} JRFileSpec;

typedef struct DLinkList {
	DLinkElement* first;
	DLinkElement* last;
} DLinkList;

typedef struct DBStringCacheIndex* DBStringCacheIndexRef;
typedef struct StringRefcount StringRefcount;
typedef struct StringOffset StringOffset;
typedef struct JRStringCache {
	unsigned magic;
	unsigned options;
	DBStringCacheIndexRef* dbIndicies;
	StringOffset** stringOffsets;
	StringRefcount** stringRefcounts;
	char** stringData;
	int numDBIndicies;
	int numOffsets;
	int firstFreeOffset;
	int extraStringData;
	unsigned dataChunkSize;
	int lockCount;
	unsigned deletedBytes;
} JRStringCache;

typedef struct SLinkElement SLinkElement;
typedef struct SLinkList {
	SLinkElement* head;
} SLinkList;

typedef struct OpaqueFixedMemAllocator OpaqueFixedMemAllocator;
typedef struct ITImageInfoLookupTable* ITImageInfoLookupTableRef;
typedef struct ITImageAlbumLookupTable* ITImageAlbumLookupTableRef;
typedef struct IPhotoAlbumMusicImportContext IPhotoAlbumMusicImportContext;
typedef struct ITImageAlbum ITImageAlbum;
typedef struct ITImageLibrary {
	unsigned _field1;
	unsigned char _field2;
	unsigned char _field3;
	unsigned char _field4;
	unsigned char _field5;
	unsigned char _field6;
	unsigned _field7;
	DLinkList _field8;
	unsigned _field9;
	ITImageAlbum* _field10;
	unsigned _field11;
	SLinkList _field12;
	unsigned _field13;
	unsigned _field14;
	OpaqueFixedMemAllocator* _field15;
	OpaqueFixedMemAllocator* _field16;
	OpaqueFixedMemAllocator* _field17;
	JRStringCache _field18;
	JRStringCache _field19;
	JRStringCache _field20[20];
	JRFileSpec _field21;
	JRFileSpec _field22;
	unsigned _field23;
	unsigned _field24;
	unsigned short _field25;
	ITImageInfoLookupTableRef _field26;
	ITImageInfoLookupTableRef _field27;
	ITImageInfoLookupTableRef _field28;
	ITImageAlbumLookupTableRef _field29;
	ITImageAlbumLookupTableRef _field30;
	IPhotoAlbumMusicImportContext* _field31;
	void* _field32;
	unsigned char _field33;
	unsigned long long _field34;
	unsigned char _field35;
	unsigned _field36;
	unsigned _field37;
	unsigned long long _field38;
	unsigned char _field39;
	unsigned long long _field40;
	unsigned long long _field41;
	unsigned long long _field42;
	unsigned _field43;
	unsigned char _field44[3070];
	unsigned char _field45;
	JRFileSpec _field46;
} ITImageLibrary;

struct SLinkElement;

typedef struct ITImageFaceInstance* ITImageFaceInstanceRef;

typedef struct OpaqueJRStringCacheIndex OpaqueJRStringCacheIndex;

typedef struct ITImageInfo {
	DLinkElement _field1;
	ITImageLibrary* _field2;
	unsigned _field3;
	unsigned _field4;
	unsigned long long _field5;
	unsigned _field6;
	unsigned _field7;
	unsigned _field8;
	unsigned _field9;
	unsigned short _field10;
	unsigned short _field11;
	SLinkList _field12;
	unsigned short _field13;
	unsigned short _field14;
	ITImageFaceInstanceRef _field15;
	void* _field16;
	unsigned char _field17;
	unsigned char _field18;
	unsigned char _field19;
	unsigned char _field20;
	unsigned _field21;
	OpaqueJRStringCacheIndex* _field22;
	unsigned _field23;
	unsigned _field24;
	unsigned _field25;
	unsigned _field26;
	unsigned _field27;
	unsigned _field28;
	unsigned _field29;
	unsigned _field30;
	unsigned char _field31;
	bool _field32;
	unsigned char _field33;
	unsigned _field34;
	double _field35;
	double _field36;
	unsigned char _field37;
} ITImageInfo;

typedef struct CGRect {
	CGPoint _field1;
	CGSize _field2;
} CGRect;

typedef struct OpaqueMessageReceiverMap OpaqueMessageReceiverMap;
typedef struct MessageSender {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
	unsigned _field4;
	DLinkList _field5;
	OpaqueMessageReceiverMap* _field6;
} MessageSender;

typedef struct OpaqueMessageSenderMap OpaqueMessageSenderMap;
template<>
struct function<void ()(OSType, void*, void*, void*)>;
typedef struct MessageReceiver {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
	DLinkList _field4;
	OpaqueMessageSenderMap* _field5;
	function<void ()(OSType, void*, void*, void*)>* _field6;
	/*function-pointer*/ void* _field7;
	void* _field8;
} MessageReceiver;

typedef struct MemHandleRecord MemHandleRecord;
typedef struct Array {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
	int _field4;
	MemHandleRecord* _field5;
	/*function-pointer*/ void* _field6;
	void* _field7;
	unsigned char _field8;
	unsigned char _field9;
} Array;

typedef struct Playlist Playlist;
typedef struct TrackInfoLookupTable TrackInfoLookupTable;
typedef struct TrackInstanceLookupTable TrackInstanceLookupTable;
typedef struct TrackInfo TrackInfo;
typedef struct AlbumInfo AlbumInfo;
typedef struct ArtistInfo ArtistInfo;
typedef struct SQLDatabase* SQLDatabaseRef;
typedef struct CDData* CDDataRef;
typedef struct TunerData TunerData;
typedef struct PlaylistLookupTable PlaylistLookupTable;
typedef struct TrackData {
	struct TrackData* _field1;
	unsigned _field2;
	AppContext* _field3;
	unsigned _field4;
	unsigned long long _field5;
	unsigned _field6;
	unsigned _field7;
	void* _field8;
	unsigned _field9;
	unsigned _field10;
	Playlist* _field11;
	Playlist* _field12;
	unsigned _field13;
	unsigned _field14;
	TrackInfo* _field15;
	TrackInfo* _field16;
	unsigned _field17;
	AlbumInfo* _field18;
	AlbumInfo* _field19;
	AlbumInfo* _field20;
	unsigned _field21;
	ArtistInfo* _field22;
	ArtistInfo* _field23;
	ArtistInfo* _field24;
	ArtistInfo* _field25;
	ArtistInfo* _field26;
	unsigned _field27 : 1;
	unsigned _field28 : 1;
	unsigned _field29 : 1;
	unsigned _field30 : 1;
	unsigned _field31 : 1;
	unsigned _field32 : 1;
	unsigned _field33 : 1;
	unsigned _field34 : 1;
	unsigned _field35 : 1;
	unsigned _field36 : 1;
	unsigned _field37 : 1;
	unsigned _field38 : 1;
	unsigned _field39 : 1;
	unsigned _field40 : 1;
	unsigned _field41 : 1;
	unsigned _field42 : 1;
	unsigned _field43 : 1;
	unsigned _field44 : 1;
	unsigned _field45 : 1;
	unsigned _field46 : 1;
	unsigned _field47 : 1;
	unsigned _field48 : 1;
	unsigned _field49 : 1;
	unsigned _field50 : 1;
	unsigned _field51 : 1;
	unsigned _field52 : 1;
	unsigned _field53 : 1;
	unsigned _field54 : 1;
	unsigned short _field55;
	unsigned char _field56;
	OpaqueFixedMemAllocator* _field57;
	OpaqueFixedMemAllocator* _field58;
	OpaqueFixedMemAllocator* _field59;
	OpaqueFixedMemAllocator* _field60;
	OpaqueFixedMemAllocator* _field61;
	OpaqueFixedMemAllocator* _field62;
	OpaqueFixedMemAllocator* _field63;
	OpaqueFixedMemAllocator* _field64;
	/*function-pointer*/ void* _field65;
	void* _field66;
	MessageSender _field67;
	MessageReceiver _field68;
	JRStringCache _field69;
	JRStringCache _field70;
	JRStringCache _field71;
	JRStringCache _field72;
	JRStringCache _field73;
	JRStringCache _field74;
	JRStringCache _field75;
	JRStringCache _field76;
	JRStringCache _field77;
	JRStringCache _field78;
	JRStringCache _field79;
	JRStringCache _field80;
	JRStringCache _field81;
	JRStringCache _field82;
	JRStringCache _field83;
	JRStringCache _field84;
	JRStringCache _field85;
	JRStringCache _field86;
	JRStringCache _field87;
	JRStringCache _field88;
	JRStringCache _field89;
	JRStringCache _field90;
	JRStringCache _field91;
	JRStringCache _field92[50];
	JRStringCache _field93;
	JRStringCache _field94;
	JRStringCache _field95;
	JRStringCache _field96;
	OpaqueJRStringCacheIndex* _field97;
	TrackInfoLookupTable* _field98;
	TrackInstanceLookupTable* _field99;
	TrackInfoLookupTable* _field100;
	TrackInfoLookupTable* _field101;
	TrackInfoLookupTable* _field102;
	unsigned short _field103[256];
	unsigned short _field104;
	JRFileSpec _field105;
	unsigned long long _field106;
	unsigned _field107 : 1;
	unsigned _field108 : 1;
	unsigned _field109 : 1;
	unsigned _field110 : 1;
	unsigned _field111 : 1;
	unsigned _field112 : 1;
	unsigned _field113 : 1;
	unsigned _field114 : 1;
	unsigned char _field115;
	unsigned _field116;
	TrackInstanceLookupTable* _field117;
	unsigned _field118;
	unsigned _field119;
	SQLDatabaseRef _field120;
	unsigned _field121;
	void* _field122;
	CFDataRef _field123;
	unsigned _field124;
	unsigned char _field125;
	union {
		CDDataRef _field1;
		TunerData* _field2;
		struct {
			unsigned _field1;
			unsigned _field2;
			unsigned long long _field3;
			unsigned long long _field4;
			unsigned long long _field5;
			unsigned char _field6;
			unsigned char _field7;
			unsigned char _field8;
			unsigned char _field9;
			unsigned short _field10;
			unsigned char _field11;
			unsigned char _field12;
		} _field3;
		void* _field4;
	} _field126;
	PlaylistLookupTable* _field127;
	PlaylistLookupTable* _field128;
	Array _field129;
} TrackData;

typedef struct VideoTrackInfo VideoTrackInfo;
typedef struct TrackInstance TrackInstance;
typedef struct PlaylistItem PlaylistItem;
typedef struct ExtendedTrackInfo ExtendedTrackInfo;
struct TrackInfo {
	struct TrackData* _field1;
	struct TrackInfo* _field2;
	struct TrackInfo* _field3;
	struct AlbumInfo* _field4;
	struct TrackInfo* _field5;
	struct TrackInfo* _field6;
	struct ArtistInfo* _field7;
	struct TrackInfo* _field8;
	struct TrackInfo* _field9;
	unsigned _field10;
	unsigned _field11;
	unsigned long long _field12;
	struct ExtendedTrackInfo* _field13;
	struct VideoTrackInfo* _field14;
	struct TrackInstance* _field15;
	unsigned char _field16;
	unsigned char _field17;
	unsigned char _field18[6];
	unsigned _field19 : 1;
	unsigned _field20 : 1;
	unsigned _field21 : 1;
	unsigned _field22 : 1;
	unsigned _field23 : 1;
	unsigned _field24 : 1;
	unsigned _field25 : 1;
	unsigned _field26 : 1;
	unsigned _field27 : 1;
	unsigned _field28 : 1;
	unsigned _field29 : 1;
	unsigned _field30 : 1;
	unsigned _field31 : 1;
	unsigned _field32 : 1;
	unsigned _field33 : 1;
	unsigned _field34 : 1;
	unsigned _field35 : 1;
	unsigned _field36 : 1;
	unsigned _field37 : 1;
	unsigned _field38 : 1;
	unsigned _field39 : 1;
	unsigned _field40 : 1;
	unsigned _field41 : 1;
	unsigned _field42 : 1;
	unsigned _field43 : 1;
	unsigned _field44 : 1;
	unsigned _field45 : 1;
	unsigned _field46 : 1;
	unsigned _field47 : 1;
	unsigned _field48 : 1;
	unsigned _field49 : 1;
	unsigned _field50 : 1;
	unsigned _field51 : 1;
	unsigned _field52 : 1;
	unsigned _field53 : 1;
	unsigned _field54 : 1;
	unsigned _field55 : 1;
	unsigned _field56 : 1;
	unsigned char _field57;
	unsigned char _field58;
	unsigned char _field59;
	unsigned char _field60;
	unsigned char _field61;
	unsigned _field62;
	void* _field63;
	unsigned _field64;
	unsigned _field65;
	unsigned _field66;
	struct PlaylistItem* _field67;
	struct OpaqueJRStringCacheIndex* _field68;
	struct OpaqueJRStringCacheIndex* _field69;
	struct OpaqueJRStringCacheIndex* _field70;
	struct OpaqueJRStringCacheIndex* _field71;
	struct OpaqueJRStringCacheIndex* _field72;
	struct OpaqueJRStringCacheIndex* _field73;
	struct OpaqueJRStringCacheIndex* _field74;
	struct OpaqueJRStringCacheIndex* _field75;
	struct OpaqueJRStringCacheIndex* _field76;
	struct OpaqueJRStringCacheIndex* _field77;
	struct OpaqueJRStringCacheIndex* _field78;
	struct OpaqueJRStringCacheIndex* _field79;
	unsigned _field80;
	unsigned _field81;
	unsigned _field82;
	unsigned _field83;
	unsigned short _field84;
	short _field85;
	short _field86;
	BOOL _field87;
	unsigned char _field88;
	BOOL _field89;
	unsigned char _field90;
	unsigned short _field91;
	unsigned short _field92;
	unsigned short _field93;
	unsigned short _field94;
	unsigned _field95;
	unsigned _field96;
	unsigned _field97;
	unsigned _field98;
	unsigned _field99;
	unsigned _field100;
	unsigned short _field101;
	unsigned short _field102;
	unsigned _field103;
	unsigned long long _field104;
	unsigned long long _field105;
	unsigned long long _field106;
	unsigned long long _field107;
	unsigned _field108;
	unsigned _field109;
	struct OpaqueJRStringCacheIndex* _field110[6];
};

struct AlbumInfo {
	unsigned _field1;
	int _field2;
	struct TrackData* _field3;
	struct AlbumInfo* _field4;
	struct AlbumInfo* _field5;
	unsigned _field6;
	struct TrackInfo* _field7;
	struct TrackInfo* _field8;
	unsigned char _field9;
	unsigned _field10;
	void* _field11;
	unsigned _field12;
	unsigned long long _field13;
	unsigned long long _field14;
	unsigned char _field15;
	unsigned char _field16;
	BOOL _field17;
	unsigned char _field18;
	unsigned _field19;
	unsigned char _field20;
	unsigned char _field21;
	struct OpaqueJRStringCacheIndex* _field22;
	struct JRStringCache* _field23;
	union {
		struct {
			unsigned _field1;
		} _field1;
		struct {
			struct OpaqueJRStringCacheIndex* _field1;
			struct OpaqueJRStringCacheIndex* _field2;
			struct OpaqueJRStringCacheIndex* _field3;
			unsigned char _field4;
		} _field2;
		struct {
			struct OpaqueJRStringCacheIndex* _field1;
			struct OpaqueJRStringCacheIndex* _field2;
			struct OpaqueJRStringCacheIndex* _field3;
		} _field3;
		struct {
			struct OpaqueJRStringCacheIndex* _field1;
			unsigned _field2;
		} _field4;
	} _field24;
	unsigned _field25;
	unsigned char _field26;
	unsigned long long _field27;
	struct TrackInfo* _field28;
	unsigned char _field29;
	unsigned char _field30;
	unsigned char _field31;
	unsigned char _field32;
};

struct ArtistInfo {
	unsigned _field1;
	int _field2;
	struct TrackData* _field3;
	struct ArtistInfo* _field4;
	struct ArtistInfo* _field5;
	unsigned _field6;
	unsigned _field7;
	unsigned _field8;
	struct TrackInfo* _field9;
	struct TrackInfo* _field10;
	unsigned char _field11;
	unsigned _field12;
	void* _field13;
	unsigned _field14;
	unsigned long long _field15;
	unsigned long long _field16;
	unsigned _field17;
	unsigned char _field18;
	unsigned char _field19;
	union {
		struct {
			unsigned _field1;
		} _field1;
		struct {
			struct OpaqueJRStringCacheIndex* _field1;
			struct OpaqueJRStringCacheIndex* _field2;
		} _field2;
	} _field20;
	unsigned _field21;
	unsigned char _field22;
	unsigned long long _field23;
	unsigned long long _field24;
	struct AlbumInfo* _field25;
	unsigned char _field26;
	unsigned char _field27;
	struct OpaqueJRStringCacheIndex* _field28;
	struct JRStringCache* _field29;
	unsigned char _field30;
	unsigned char _field31;
	unsigned char _field32;
};

struct ExtendedTrackInfo;

struct VideoTrackInfo;

struct TrackInstance;

struct PlaylistItem {
	struct Playlist* _field1;
	struct PlaylistItem* _field2;
	struct PlaylistItem* _field3;
	struct PlaylistItem* _field4;
	unsigned _field5;
	struct TrackInfo* _field6;
	void* _field7;
	unsigned _field8;
	unsigned char _field9;
	unsigned _field10 : 1;
	unsigned _field11 : 1;
	unsigned _field12 : 1;
	unsigned _field13 : 1;
	unsigned _field14 : 1;
	unsigned _field15 : 1;
	unsigned _field16 : 1;
	unsigned _field17 : 1;
	unsigned _field18 : 1;
	unsigned _field19 : 1;
	unsigned _field20 : 1;
	unsigned _field21 : 1;
	unsigned _field22 : 1;
	unsigned _field23 : 1;
	unsigned _field24 : 1;
	unsigned _field25 : 1;
	unsigned _field26 : 1;
	unsigned _field27 : 1;
	unsigned _field28 : 1;
	unsigned _field29 : 1;
	unsigned _field30 : 1;
	unsigned char _field31;
	unsigned char _field32;
	unsigned _field33;
	unsigned _field34;
	struct PlaylistItem* _field35;
	union {
		struct {
			struct PlaylistItem* _field1;
			struct PlaylistItem* _field2;
			unsigned _field3;
			unsigned _field4;
			struct OpaqueJRStringCacheIndex* _field5;
			struct OpaqueJRStringCacheIndex* _field6;
			unsigned char _field7;
			union {
				struct {
					short _field1;
					unsigned short _field2;
					unsigned _field3 : 1;
					unsigned _field4 : 1;
					unsigned _field5 : 1;
					unsigned _field6 : 1;
					unsigned _field7 : 1;
				} _field1;
				struct {
					unsigned long long _field1;
				} _field2;
			} _field8;
		} _field1;
		struct {
			unsigned _field1;
			struct TrackInstance* _field2;
			unsigned char _field3;
			union {
				struct {
					unsigned _field1;
				} _field1;
			} _field4;
		} _field2;
	} _field36;
};

typedef struct ITObjectList* ITObjectListRef;
typedef struct SearchCriteriaList SearchCriteriaList;
typedef struct SmartPlaylistOptions {
	unsigned char _field1;
	unsigned char _field2;
	unsigned char _field3;
	unsigned char _field4;
	unsigned char _field5;
	SearchCriteriaList* _field6;
	ITObjectListRef _field7;
	unsigned _field8;
	unsigned char _field9;
	unsigned _field10;
	unsigned char _field11;
} SmartPlaylistOptions;

typedef struct TrackBitFields {
	unsigned char _field1[24];
} TrackBitFields;

typedef struct PlaylistIndexLookupTable PlaylistIndexLookupTable;
typedef struct PlaylistItemLookupTable PlaylistItemLookupTable;
typedef struct PlaylistLookupTableEntry {
	unsigned _field1;
	unsigned _field2;
	unsigned char _field3;
	TrackBitFields _field4;
	PlaylistItemLookupTable* _field5;
	PlaylistIndexLookupTable* _field6;
} PlaylistLookupTableEntry;

typedef struct PlaylistLookupTableInfo {
	PlaylistLookupTableEntry _field1;
	Array _field2;
} PlaylistLookupTableInfo;

typedef struct PlaylistColumnSet PlaylistColumnSet;
typedef struct PlaylistColumnSetsHandler {
	unsigned _field1;
	int _field2;
	SLinkList _field3;
	PlaylistColumnSet* _field4;
	unsigned _field5;
	unsigned char _field6;
} PlaylistColumnSetsHandler;

typedef struct PlaylistColumnBrowseInfo {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3[6];
	unsigned _field4[6];
	unsigned _field5[6];
} PlaylistColumnBrowseInfo;

typedef struct PlaylistPermissions {
	TrackBitFields _field1;
	unsigned _field2 : 1;
	unsigned _field3 : 1;
	unsigned _field4 : 1;
	unsigned _field5 : 1;
	unsigned _field6 : 1;
	unsigned _field7 : 1;
	unsigned _field8 : 1;
	unsigned _field9 : 1;
	unsigned _field10 : 1;
	unsigned _field11 : 1;
	unsigned _field12 : 1;
} PlaylistPermissions;

typedef struct StorePageContext StorePageContext;
typedef struct PlayFilter PlayFilter;
struct Playlist {
	unsigned _field1;
	struct AppContext* _field2;
	struct TrackData* _field3;
	struct Playlist* _field4;
	struct Playlist* _field5;
	struct Playlist* _field6;
	unsigned _field7;
	struct Playlist* _field8;
	struct Playlist* _field9;
	unsigned _field10;
	void* _field11;
	unsigned _field12;
	unsigned long long _field13;
	unsigned _field14;
	struct OpaqueFixedMemAllocator* _field15;
	struct OpaqueFixedMemAllocator* _field16;
	struct PlaylistItem* _field17;
	struct PlaylistItem* _field18;
	struct MessageSender _field19;
	struct MessageReceiver _field20;
	struct TrackBitFields _field21;
	struct TrackBitFields _field22;
	struct JRStringCache _field23;
	struct OpaqueJRStringCacheIndex* _field24;
	struct OpaqueJRStringCacheIndex* _field25;
	unsigned short _field26;
	unsigned short _field27;
	unsigned _field28;
	int _field29;
	unsigned _field30 : 1;
	unsigned _field31 : 1;
	unsigned _field32 : 1;
	unsigned _field33 : 1;
	unsigned _field34 : 1;
	unsigned _field35 : 1;
	unsigned _field36 : 1;
	unsigned _field37 : 1;
	unsigned _field38 : 1;
	unsigned _field39 : 1;
	unsigned _field40 : 1;
	unsigned _field41 : 1;
	unsigned _field42 : 1;
	unsigned _field43 : 1;
	unsigned _field44 : 1;
	unsigned _field45 : 1;
	unsigned _field46 : 1;
	unsigned char _field47;
	/*function-pointer*/ void* _field48;
	void* _field49;
	unsigned _field50;
	unsigned _field51;
	unsigned _field52;
	unsigned short _field53;
	unsigned _field54;
	unsigned _field55;
	unsigned _field56;
	unsigned long long _field57;
	unsigned long long _field58;
	unsigned long long _field59;
	unsigned _field60 : 1;
	unsigned _field61 : 1;
	unsigned _field62 : 1;
	unsigned _field63 : 1;
	unsigned char _field64;
	unsigned char _field65;
	struct SmartPlaylistOptions _field66;
	struct TrackBitFields _field67;
	struct MessageReceiver _field68;
	unsigned _field69 : 1;
	unsigned _field70 : 1;
	unsigned _field71 : 1;
	unsigned _field72 : 1;
	unsigned _field73 : 1;
	unsigned _field74 : 1;
	unsigned _field75 : 1;
	unsigned _field76 : 1;
	unsigned _field77 : 1;
	unsigned _field78 : 1;
	unsigned _field79 : 1;
	unsigned _field80 : 1;
	unsigned _field81 : 1;
	unsigned _field82 : 1;
	unsigned _field83 : 1;
	unsigned _field84 : 1;
	unsigned _field85 : 1;
	unsigned _field86 : 1;
	struct StorePageContext* _field87;
	struct SearchCriteriaList* _field88;
	struct PlayFilter* _field89;
	unsigned char _field90;
	struct SearchCriteriaList* _field91;
	unsigned short _field92;
	unsigned long long _field93;
	int _field94;
	unsigned _field95;
	unsigned _field96;
	unsigned _field97;
	unsigned _field98;
	struct PlaylistItemLookupTable* _field99;
	unsigned long long _field100[6];
	unsigned long long _field101[4];
	void* _field102;
	unsigned _field103 : 1;
	unsigned _field104 : 1;
	struct PlaylistItemLookupTable* _field105;
	unsigned _field106;
	unsigned _field107;
	struct PlaylistLookupTableInfo _field108;
	struct PlaylistColumnSetsHandler _field109;
	struct PlaylistColumnBrowseInfo _field110;
	unsigned char _field111;
	struct PlaylistPermissions _field112;
	unsigned _field113;
	unsigned _field114;
	unsigned char _field115;
	unsigned char _field116;
	union {
		struct {
			unsigned _field1;
			ITObjectListRef _field2;
			unsigned _field3;
		} _field1;
		struct {
			unsigned _field1;
		} _field2;
	} _field117;
};

struct OpaqueFixedMemAllocator;

struct OpaqueMessageReceiverMap;

struct OpaqueMessageSenderMap;

template<>
struct function<void ()(OSType, void*, void*, void*)>;

struct DBStringCacheIndex;

struct StringOffset;

struct StringRefcount;

struct SearchCriteriaList;

struct ITObjectList;

struct StorePageContext;

struct PlayFilter;

struct PlaylistItemLookupTable;

struct PlaylistIndexLookupTable;

struct MemHandleRecord;

struct PlaylistColumnSet;

struct TrackInfoLookupTable;

struct TrackInstanceLookupTable;

struct JRFileSpecFunctionTable;

struct SQLDatabase;

struct CDData;

struct TunerData;

struct PlaylistLookupTable;

typedef struct ITImageAlbumItem* ITImageAlbumItemRef;
struct ITImageAlbum {
	struct ITImageAlbum* _field1;
	struct ITImageLibrary* _field2;
	unsigned char _field3;
	unsigned char _field4;
	unsigned short _field5;
	unsigned _field6;
	unsigned long long _field7;
	unsigned long long _field8;
	unsigned long long _field9;
	unsigned _field10;
	ITImageAlbumItemRef _field11;
	void* _field12;
	struct OpaqueJRStringCacheIndex* _field13;
	unsigned char _field14;
	unsigned char _field15;
	unsigned char _field16;
	unsigned char _field17;
	BOOL _field18;
	unsigned _field19;
	unsigned _field20;
	struct OpaqueJRStringCacheIndex* _field21;
	unsigned long long _field22;
	unsigned long long _field23;
	unsigned _field24;
	unsigned _field25;
	unsigned _field26;
	unsigned long long _field27;
	unsigned short _field28;
	unsigned short _field29;
	CFDataRef _field30;
	unsigned _field31;
	unsigned _field32;
	unsigned _field33;
	unsigned char _field34;
	unsigned char _field35;
};

struct ITImageAlbumItem;

typedef struct __CFDictionary* CFDictionaryRef;

struct ITImageInfoLookupTable;

struct ITImageAlbumLookupTable;

struct IPhotoAlbumMusicImportContext;

typedef struct ITStreamInfo {
	int _field1;
	unsigned short _field2[256];
	unsigned short _field3[256];
	unsigned short _field4[256];
} ITStreamInfo;

typedef struct BRTimeRange {
	double _field1;
	double _field2;
} BRTimeRange;

typedef struct __ATVMediaCollection* ATVMediaCollectionRef;

typedef struct __ATVMediaQuery* ATVMediaQueryRef;

typedef struct __ATVDataClient* ATVDataClientRef;

typedef struct _OSMemoryNotification* OSMemoryNotificationRef;

typedef struct __SCDynamicStore* SCDynamicStoreRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct __SCPreferences* SCPreferencesRef;

typedef struct _opaque_pthread_mutex_t {
	long __sig;
	BOOL __opaque[40];
} opaque_pthread_mutex_t;

typedef struct {
	long long _field1;
	int _field2;
	unsigned _field3;
	long long _field4;
} XXStruct_oHBkXC;

typedef struct ITITunesInfo {
	unsigned long long _field1;
	unsigned long long _field2;
	unsigned long long _field3;
} ITITunesInfo;

typedef struct __ATVMediaType* ATVMediaTypeRef;


