/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MediaControlServerDelegate.h"
#import "LTAirVideoAgent.h"
#import <BackRow/BRSingleton.h>

@class NSURL, MediaControlServer;

@interface LTAirVideoAgent : BRSingleton <MediaControlServerDelegate> {
	NSURL* _currentURL;
	MediaControlServer* _server;
	unsigned _fpContextID;
	BOOL _fpContextIDValid;
}
+(id)singleton;
+(void)setSingleton:(id)singleton;
-(id)init;
-(void)dealloc;
@end

@interface LTAirVideoAgent (Private)
-(void)mediaControlServer:(id)server playURL:(id)url position:(float)position playInfo:(id)info sessionID:(unsigned long long)anId;
-(void)mediaControlServer:(id)server stopWithOptions:(unsigned)options;
-(void)mediaControlServer:(id)server setRate:(float)rate;
-(void)mediaControlServer:(id)server getPosition:(float*)position duration:(float*)duration;
-(void)mediaControlServer:(id)server setPosition:(float)position;
-(void)mediaControlServer:(id)server getVolume:(float*)volume;
-(void)mediaControlServer:(id)server setVolume:(float)volume;
-(void)mediaControlServer:(id)server showPhotoAtPath:(id)path;
-(void)_airPlayPreferenceChanged:(id)changed;
-(void)_playerStateChanged:(id)changed;
-(void)_playerPlaybackError:(id)error;
-(BOOL)_playingAirVideoItem;
-(void)_userAction;
-(long)_initFairPlayWithPath:(const char*)path contextID:(unsigned*)anId;
-(BOOL)_isAppleInternalBuild;
@end

