/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRMediaPlayer.h>
#import "Lowtide-Structs.h"
#import "LTAVPlayer.h"

@class LTAVPlaylist, NSString, BRControl, NSArray, NSMutableArray, LTVideoVisualControl, NSTimer, NSMutableDictionary, AVQueuePlayer, AVPlayerItem, AVAsset, NSThread, LTTrickPlayPlayer;
@protocol BRMediaCollection;

@interface LTAVPlayer : BRMediaPlayer {
	AVQueuePlayer* _player;
	int _playerItemStatus;
	LTVideoVisualControl* _avPlayerVisuals;
	BRControl* _trickPlayVisuals;
	AVPlayerItem* _currentItem;
	AVAsset* _avAssetBeingCached;
	LTAVPlaylist* _playlist;
	id<BRMediaCollection> _mediaCollection;
	NSMutableDictionary* _observedObjects;
	NSThread* _originatingThread;
	NSTimer* _movieExpirationTimer;
	id _timeObserverToken;
	NSString* _keyBagPath;
	NSArray* _selectableAudioTracks;
	NSArray* _chapters;
	NSArray* _subtitleTracks;
	NSMutableArray* _fairPlayContexts;
	int _defaultActionAtItemEnd;
	NSTimer* _HDCPPollTimer;
	BOOL _skipHDCPCheck;
	NSTimer* _activityTimer;
	LTTrickPlayPlayer* _trickPlayPlayer;
	double _virtualChapterMark;
	long _lastRetrievedChapterIndex;
	int _state;
	int _repeatMode;
	BOOL _playbackInitiated;
	BOOL _playingBackInitialItem;
	BOOL _playheadAdvanced;
	BOOL _muted;
	BOOL _inTrickPlayMode;
	BOOL _hasRealChapters;
	BOOL _waitingForPlayerToCatchUpAfterEmergingFromTrickPlay;
	BOOL _currentlySeeking;
	BOOL _waitingForPlayerAdvance;
	int _numPendingRateRequests;
	NSTimer* _expirationTimer;
}
+(void)initialize;
+(id)contentTypes;
+(BOOL)allowMultiplePlayers;
-(id)init;
-(void)dealloc;
-(BOOL)setMediaAtIndex:(long)index inCollection:(id)collection error:(id*)error;
-(BOOL)setMediaAtIndex:(long)index inTrackList:(id)trackList error:(id*)error;
-(void)appendMediaToSlidingWindow:(id)slidingWindow;
-(id)collection;
-(id)media;
-(id)trackList;
-(long)mediaIndex;
-(BOOL)cueMediaWithError:(id*)error;
-(BOOL)setState:(int)state error:(id*)error;
-(int)playerState;
-(BOOL)supportsMultipleTrickSpeeds;
-(BOOL)supportsTrickPlay;
-(double)duration;
-(void)setElapsedTime:(double)time;
-(double)elapsedTime;
-(void)resetToBeginning;
-(BOOL)hasChapters;
-(id)chapterTimes;
-(void)setVirtualChapterMark:(double)mark;
-(double)virtualChapterMark;
-(void)nextChapter;
-(void)previousChapter;
-(void)setCurrentChapterIndex:(long)index;
-(BOOL)hasRealChapters;
-(BOOL)hasChapterPictures;
-(BOOL)chapterIsPlayable:(long)playable;
-(long)chapterCount;
-(long)currentChapterIndex;
-(long)chapterIndexForTime:(double)time;
-(id)currentChapterTitle;
-(id)chapterTitleForIndex:(long)index;
-(id)chapterImageProxyForIndex:(long)index;
-(double)startTimeForChapter:(long)chapter;
-(double)endTimeForChapter:(long)chapter;
-(BOOL)supportsBufferedRange;
-(BRTimeRange)bufferedRange;
-(float)bufferingProgress;
-(void)setMuted:(BOOL)muted;
-(BOOL)muted;
-(id)currentVideoFrame;
-(BOOL)attemptAuthorizationWithError:(id*)error;
-(BOOL)playingVisualContent;
-(id)visuals;
-(void)previousMedia;
-(void)nextMedia;
-(void)setShufflePlayback:(BOOL)playback;
-(BOOL)shufflePlayback;
-(BOOL)supportsShufflePlayback;
-(void)setRepeatMode:(int)mode;
-(int)repeatMode;
-(BOOL)supportsRepeatModes;
-(void)setSkipExplicit:(BOOL)anExplicit;
-(BOOL)skipExplicit;
-(id)subtitleTrackIDs;
-(id)displayStringForSubtitleTrackID:(long)subtitleTrackID;
-(void)setSelectedSubtitleTrackID:(long)anId;
-(long)selectedSubtitleTrackID;
-(id)audioTrackIDs;
-(id)displayStringForAudioTrackID:(long)audioTrackID;
-(void)setSelectedAudioTrackID:(long)anId;
-(long)selectedAudioTrackID;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
@end

@interface LTAVPlayer (KVO)
-(void)_addObserverForObject:(id)object forKeyPath:(id)keyPath options:(unsigned)options context:(void*)context;
-(void)_removeAllObserversForObject:(id)object;
@end

@interface LTAVPlayer (Expiration)
-(void)_movieExpirationDateSet:(id)set;
-(void)_enforceMovieExpirationPolicy:(id)policy;
@end

@interface LTAVPlayer (Notifications)
-(void)_playerItemDidPlayToEnd:(id)_playerItem;
-(void)_playerItemFailedToPlayToEnd:(id)end;
-(void)_playerItemDidChange;
-(void)_playerRateDidChange;
-(void)_playerItemStatusDidChange;
-(void)_timedMetadataDidChange;
-(void)_loadedTimeRangesDidChange;
-(void)_playerItemTracksDidChange;
-(void)_playbackLikelyToKeepUp;
-(void)_playbackBufferFull;
-(BOOL)_isPlaybackBufferEmpty;
-(void)_playbackBufferEmpty;
-(void)_stallHasOccurred;
-(void)_sendPlaybackEndedNotification;
-(void)_sendTimeSkippedNotification;
-(void)_sendVisualControlChangedNotification;
-(void)_sendStateChangedNotification;
-(void)_sendAssetChangedNotification;
-(void)_sendAssetStalledNotification:(id)notification;
@end

@interface LTAVPlayer (AudioSubtitlesChapters)
-(void)_updateChapters;
-(void)_updateClosedCaptions;
-(void)_generateFakeChapters;
-(long)_chapterIndexForTime:(double)time startSearchFrom:(long)from;
@end

@interface LTAVPlayer (PlaybackControl)
-(void)_disposePlayer;
-(void)_setPlayerItem:(id)item;
-(void)_updateTrickPlayPlayer;
-(void)_updateVisuals:(BOOL)visuals;
-(BOOL)_currentItemPlayable;
-(void)_emergeFromLoadingState;
-(void)_postError:(id)error stopPlayer:(BOOL)player;
-(BOOL)_handleStopActionWithError:(id*)error;
-(BOOL)_handlePauseActionWithError:(id*)error;
-(BOOL)_handlePlayActionWithError:(id*)error;
-(BOOL)_handleRateChangeState:(int)state error:(id*)error;
-(int)_resumeStateForState:(int)state;
-(BOOL)_setNewState:(int)state error:(id*)error;
-(void)_handleRateChangeToRate:(float)rate;
-(void)_handleRateChangeToRate:(float)rate enterTrickPlay:(BOOL)play;
-(void)_handleReentryIntoRegularPlayWithRate:(float)rate;
-(BOOL)_initializePlayer:(id*)player;
-(void)_changeMedia:(int)media;
-(double)_currentChapterMark;
-(double)_previousChapterMark;
-(double)_nextChapterMark;
-(id)_playerItemForAsset:(id)asset;
-(void)_removeLookAheadPlayerItem;
-(void)_updateFairplayContext;
-(BOOL)_isFastForwardingOrRewinding;
-(BOOL)_isFastForwarding;
-(BOOL)_isRewinding;
-(void)_pollHDCPStatus;
-(void)_tickleHomeShareActivity;
-(float)_rateForState:(int)state;
-(void)_setElapsedTime:(double)time snapToKeyFrameAhead:(BOOL)keyFrameAhead;
-(BOOL)_assetIsLiveStreaming:(id)streaming;
-(void)_stopPlayer:(id)player;
-(void)_setAVPlayerRate:(float)rate;
-(void)_deactivateAudioSession;
-(void)_postErrorDelayed:(id)delayed;
-(void)_deauthorizeAsset:(id)asset;
-(void)_setChapters:(id)chapters;
@end

