/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTAVPlaylist.h"
#import <Foundation/NSObject.h>

@class LTAVPlayer, NSArray;

@interface LTAVPlaylist : NSObject {
	NSArray* _mediaList;
	NSArray* _shuffleIndexes;
	LTAVPlayer* _player;
	long _sequentialIndex;
	BOOL _shuffleEnabled;
	int _repeatMode;
	BOOL _skipExplicit;
}
+(id)generateShuffleIndexesForCollectionCount:(unsigned)collectionCount;
-(id)initWithIndex:(long)index inMediaList:(id)mediaList;
-(void)dealloc;
-(void)setPlayer:(id)player;
-(id)mediaList;
-(void)appendMediaToSlidingWindow:(id)slidingWindow;
-(void)setShuffleEnabled:(BOOL)enabled;
-(BOOL)shuffleEnabled;
-(void)setRepeatMode:(int)mode;
-(int)repeatMode;
-(void)setSkipExplicit:(BOOL)anExplicit;
-(BOOL)skipExplicit;
-(long)mediaIndex;
-(long)count;
-(id)currentMedia;
-(id)nextMedia;
-(BOOL)moreItemsAvailable;
-(id)changeMedia:(int)media;
-(BOOL)isEqual:(id)equal;
@end

@interface LTAVPlaylist (Private)
-(BOOL)_assetValidForPlayback:(id)playback;
-(long)_sequentialIndex;
-(long)_mediaIndexForSequentialIndex:(long)sequentialIndex;
-(id)_mediaForSequentialIndex:(long)sequentialIndex;
-(long)_nextSequentialIndexInDirection:(int)direction;
@end

