/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTAVChapter.h"
#import <Foundation/NSObject.h>

@class NSString, AVMetadataItem;

@interface LTAVChapter : NSObject {
	NSString* _name;
	NSString* _assetID;
	AVMetadataItem* _titleMetadataItem;
	AVMetadataItem* _imageMetadataItem;
	double _startTime;
	double _endTime;
}
+(id)chapterWithName:(id)name assetID:(id)anId startTime:(double)time endTime:(double)time4;
+(id)chapterWithTimedMetadataGroup:(id)timedMetadataGroup assetID:(id)anId;
-(id)initWithName:(id)name assetID:(id)anId startTime:(double)time endTime:(double)time4;
-(void)dealloc;
-(void)invalidate;
-(id)name;
-(double)startTime;
-(double)endTime;
-(BOOL)containsTime:(double)time;
-(BOOL)hasImage;
-(id)imageProxy;
@end

@interface LTAVChapter (Private)
-(void)_setImageMetadataItem:(id)item;
-(void)_setTitleMetadataItem:(id)item;
@end

