/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "BRDownload.h"

@class NSTimer, NSURLConnection, NSHTTPURLResponse, NSDictionary, NSString, NSMutableArray;
@protocol LTNetworkTestDownloadDelegate;

@interface LTDownloadTestConnection : NSObject <BRDownload> {
	double _startTime;
	double _receivedResponseTime;
	double _elapsedTime;
	unsigned _lastMarkedLength;
	double _endTime;
	NSTimer* _measuringTimer;
	NSString* _urlString;
	NSDictionary* _options;
	NSURLConnection* _urlConnection;
	unsigned _fetchedDataLength;
	NSHTTPURLResponse* _urlResponse;
	NSMutableArray* _progressArray;
	int _downloadState;
	id<LTNetworkTestDownloadDelegate> _delegate;
}
-(void)dealloc;
-(id)init;
-(id)initWithURLString:(id)urlstring;
-(id)initWithURLString:(id)urlstring andOptions:(id)options;
-(double)startTime;
-(double)elapsedTime;
-(unsigned)fetchedDataLength;
-(unsigned)expectedContentLength;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void)startConnection;
-(void)stopConnection;
-(void)markProgress;
-(id)contentType;
-(id)progressLogs;
-(id)response;
-(id)options;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(id)connection:(id)connection willCacheResponse:(id)response;
-(int)downloadState;
-(int)qualifiedDownloadState;
-(int)downloadStateContext;
-(unsigned long long)expectedSize;
-(unsigned long long)byteCount;
-(double)timeUntilPlayable;
-(void)setPlayable:(BOOL)playable;
-(void)pause;
-(void)resume;
-(BOOL)testContent;
@end

