/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTImageTrickPlayPlayer.h"
#import "Lowtide-Structs.h"
#import "LTTrickPlayPlayer.h"


@interface LTImageTrickPlayPlayer : LTTrickPlayPlayer {
}
-(id)initWithTrickPlayAsset:(id)trickPlayAsset;
-(void)setRate:(float)rate;
-(void)bufferAheadFromTime:(XXStruct_oHBkXC)time;
-(void)bufferAheadFromTime:(XXStruct_oHBkXC)time withPreloadedImageCount:(int)preloadedImageCount atInterval:(int)interval;
-(BOOL)shouldHandleAllTrickPlay;
-(BOOL)canHandleRewindTrickPlayWithImages;
@end

@interface LTImageTrickPlayPlayer (Private)
-(void)_updatePlayer:(id)player;
-(void)_showImageForTime:(double)time;
@end

