/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRDownloadManager.h>
#import "LTITunesDownloadTestManager.h"
#import "LTNetworkTestDownloadDelegate.h"

@class NSHTTPCookie, NSDateFormatter, NSDictionary, NSString, LTDownloadTestConnection, NSArray, NSMutableArray;

@interface LTITunesDownloadTestManager : BRDownloadManager <LTNetworkTestDownloadDelegate> {
	NSDictionary* _uploadUserInput;
	NSArray* _downloadURLs;
	NSString* _speedTestGUID;
	unsigned _currentNetworkDownloadDataCount;
	unsigned _currentNetworkUploadDataCount;
	BOOL _networkDownloadInProgress;
	BOOL _networkUploadInProgress;
	NSMutableArray* _uploadLogData;
	LTDownloadTestConnection* _currentDownloadConnection;
	NSHTTPCookie* _downloadKeyCookie;
	NSDateFormatter* _dateFormat;
}
-(void)dealloc;
-(id)init;
-(BOOL)networkDiagnosticsAvailable;
-(void)startNetworkSpeedTestWithUserInput:(id)userInput;
-(void)cancelNetworkSpeedTest;
-(void)connection:(id)connection didDownloadNumberOfBytes:(unsigned)bytes atTime:(double)time;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
@end

@interface LTITunesDownloadTestManager (UploadDiagnostics)
-(id)augmentDownloadInfoWithExtraData:(id)extraData;
-(id)dictionaryForDownload:(id)download;
@end

@interface LTITunesDownloadTestManager (Private)
-(BOOL)_startNextDownloadTest;
-(void)_pauseAllDownloads;
-(void)_resumeAllDownloads;
-(id)_generateGUID;
-(unsigned long long)_preferredAccountDSID;
-(void)_uploadNetworkSamplingData;
-(void)_sendNextUploadLog;
-(unsigned long long)_lastDSIDUsedForDownload;
@end

