/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTLanguageController.h"
#import <BackRow/BRViewController.h>


@interface LTLanguageController : BRViewController {
}
-(id)init;
-(void)dealloc;
-(void)wasPushed;
-(BOOL)brEventAction:(id)action;
-(void)languageSelected:(id)selected;
@end

@interface LTLanguageController (Private)
-(void)_showLanguageChooser;
@end

