/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTMemoryUsageMonitor.h"
#import <Foundation/NSObject.h>

@class NSTimer;

@interface LTMemoryUsageMonitor : NSObject {
	NSTimer* _timer;
}
+(void)checkAndStartMonitoring;
-(void)dealloc;
@end

@interface LTMemoryUsageMonitor (Private)
-(void)_startMonitoring;
-(void)_emitMemoryUsage;
@end

