/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ATVTCPIPConfigDelegate.h"
#import "BRMenuListItemProvider.h"
#import "LTNetworkFailureController.h"
#import <BackRow/BRMenuController.h>

@class BRAirportNetwork, NSString;

@interface LTNetworkFailureController : BRMenuController <BRMenuListItemProvider, ATVTCPIPConfigDelegate> {
	BRAirportNetwork* _network;
	BOOL _localNetworkUp;
	NSString* _popToLabel;
}
-(id)initForNetwork:(id)network withPopToLabel:(id)label;
-(void)dealloc;
-(void)itemSelected:(long)selected;
-(id)itemForRow:(long)row;
-(long)itemCount;
-(id)titleForRow:(long)row;
-(float)heightForRow:(long)row;
-(BOOL)rowSelectable:(long)selectable;
-(void)configurationComplete:(BOOL)complete;
@end

@interface LTNetworkFailureController (Private)
-(void)_setTitleAndPromptStrings;
@end

