/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTNTPStartupController.h"
#import <BackRow/BRTextWithSpinnerController.h>
#import "Lowtide-Structs.h"


@interface LTNTPStartupController : BRTextWithSpinnerController {
	int _notificationToken;
	CFRunLoopSourceRef _notificationRLS;
}
-(id)init;
-(void)dealloc;
@end

@interface LTNTPStartupController (Private)
-(void)_timeChangeNotification:(id)notification;
-(void)_networkChanged:(id)changed;
@end

