/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTWirelessSetupResultDelegate.h"
#import "ATVAPTestResultDelegate.h"
#import "LTSetupWelcomeController.h"
#import <BackRow/BRController.h>


@interface LTSetupWelcomeController : BRController <ATVAPTestResultDelegate, LTWirelessSetupResultDelegate> {
	BRController* _netSetupController;
	BOOL _isNetworkSetupDone;
	BOOL _didNetworkSetupSucceed;
	BOOL _wasNetworkTested;
}
-(id)init;
-(void)dealloc;
-(void)wasPushed;
-(void)wasPopped;
-(void)wasExhumed;
-(BOOL)brEventAction:(id)action;
-(void)testCompleted:(BOOL)completed;
-(void)wirelessSetupFailed;
-(void)wirelessSetupSucceeded;
@end

@interface LTSetupWelcomeController (Private)
-(void)_showLanguageChooser;
-(void)_popToTop:(id)top;
-(void)_popToNetworkSetup:(id)networkSetup;
-(void)_setupNetworking;
-(void)_startNetworkTest;
-(void)_setupDone:(id)done;
@end

