/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRControl.h>

@class BRImageControl;

@interface LTSkipAssetVisualControl : BRControl {
	BRImageControl* _imageControl;
}
-(id)init;
-(void)dealloc;
-(void)setImage:(id)image;
-(void)layoutSubcontrols;
@end

