/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTSpringboardServices.h"
#import <BackRow/BRSingleton.h>
#import "Lowtide-Structs.h"

@class NSDictionary;

@interface LTSpringboardServices : BRSingleton {
	NSDictionary* _capabilities;
	OSMemoryNotificationRef _notificationRef;
}
+(id)singleton;
+(void)setSingleton:(id)singleton;
+(void)configureAggregateReporting;
+(void)configureGraphicsCapabilities;
+(void)monitorOSMemoryNotifications;
-(void)dealloc;
@end

@interface LTSpringboardServices (Private)
-(void)_updateCapabilities;
-(void)_registerForOSMemoryNotifications;
-(void)_waitForOSMemoryNotifcation;
-(void)_postOSMemoryNotifcationForLevel:(id)level;
@end

