/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRControl.h>

@class BRImageControl, BRTextControl, NSMutableDictionary;

@interface LTThermalIndicatorControl : BRControl {
	NSMutableDictionary* _textAttrs;
	BRImageControl* _background;
	BRTextControl* _level;
}
-(id)init;
-(void)dealloc;
-(void)layoutSubcontrols;
@end

