/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "LTTrickPlayPlayer.h"
#import "Lowtide-Structs.h"

@class NSTimer, LTSkipAssetVisualControl, LTTrickPlayAsset, NSMutableDictionary, LTAVPlayer;

@interface LTTrickPlayPlayer : NSObject {
	NSTimer* _playTimer;
	double _duration;
	BOOL _didSetLayerContents;
	LTTrickPlayAsset* _asset;
	LTSkipAssetVisualControl* _visuals;
	float _rate;
	double _previousTimeIntervalCheck;
	double _currentTimeInterval;
	NSMutableDictionary* _cachedChapterImageProxies;
	LTAVPlayer* _avPlayer;
}
+(id)trickPlayerWithAsset:(id)asset;
-(id)initWithTrickPlayAsset:(id)trickPlayAsset;
-(void)dealloc;
-(void)invalidate;
-(id)avPlayer;
-(void)setAVPlayer:(id)player;
-(void)setRate:(float)rate;
-(float)rate;
-(void)seekToTime:(XXStruct_oHBkXC)time;
-(XXStruct_oHBkXC)currentTime;
-(id)visuals;
-(void)bufferAheadFromTime:(XXStruct_oHBkXC)time;
-(BOOL)shouldHandleAllTrickPlay;
-(BOOL)canHandleRewindTrickPlayWithImages;
@end

@interface LTTrickPlayPlayer (Private)
-(void)_updatePlayer:(id)player;
-(BOOL)_hasChapterImages;
@end

@interface LTTrickPlayPlayer (Protected)
-(void)_postUpdateProgress;
-(void)_checkAtEitherEndOfPlayback;
-(void)_resetVisuals;
@end

