/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LTTrickPlayAsset.h"
#import <Foundation/NSObject.h>

@class NSURL;
@protocol BRMediaAsset;

@interface LTTrickPlayAsset : NSObject {
	NSURL* _url;
	id<BRMediaAsset> _mediaAsset;
}
+(id)assetForAsset:(id)asset;
-(void)dealloc;
-(id)initWithURL:(id)url;
-(id)mediaAsset;
@end

@interface LTTrickPlayAsset (Private)
-(void)setMediaAsset:(id)asset;
@end

