/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "BRImageProxy.h"

@class AVMetadataItem, NSString;

@interface LTVideoChapterImageProxy : NSObject <BRImageProxy> {
	NSString* _identifier;
	AVMetadataItem* _metadataItem;
}
+(id)imageProxyWithIdentifier:(id)identifier metadataItem:(id)item;
-(id)initWithIdentifier:(id)identifier metadataItem:(id)item;
-(void)dealloc;
-(id)imageIDForImageSize:(int)imageSize;
-(id)imageForImageSize:(int)imageSize;
-(id)defaultImageForImageSize:(int)imageSize;
-(BOOL)supportsImageForImageSize:(int)imageSize;
-(void)cancelImageRequestsForImageSizes:(int)imageSizes;
-(id)object;
@end

