/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ATVAPNetworkSelectionDelegate.h"
#import "LTWirelessSetupController.h"
#import <BackRow/BRViewController.h>

@protocol LTWirelessSetupResultDelegate;

@interface LTWirelessSetupController : BRViewController <ATVAPNetworkSelectionDelegate> {
	id<LTWirelessSetupResultDelegate> _delegate;
	BOOL _didJoinNetwork;
}
-(void)dealloc;
-(id)init;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void)wasPushed;
-(void)wasPopped;
-(void)wasExhumed;
-(void)network:(id)network wasSelected:(BOOL)selected;
@end

@interface LTWirelessSetupController (Private)
-(void)_showNetworkMenu;
@end

