/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRBaseMediaProvider.h>

@class MEAirTunesMediaAsset;

@interface MEAirTunesMediaProvider : BRBaseMediaProvider {
	MEAirTunesMediaAsset* _asset;
}
-(id)init;
-(void)dealloc;
-(id)mediaTypes;
-(int)status;
-(id)objectsWithEntityName:(id)entityName qualifiedByPredicate:(id)predicate sortDescriptors:(id)descriptors excludeHiddenObjects:(BOOL)objects error:(id*)error;
@end

