/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRBaseMediaAsset.h>

@class BRImage, NSMutableDictionary;

@interface MEAirTunesMediaAsset : BRBaseMediaAsset {
	NSMutableDictionary* _info;
	double _timestamp;
	BRImage* _coverArt;
}
-(id)initWithMediaProvider:(id)mediaProvider;
-(void)dealloc;
-(id)imageProxy;
-(BOOL)setObject:(id)object forKey:(id)key;
-(void)updateTimestamp;
-(id)assetID;
-(id)title;
-(id)artist;
-(id)composer;
-(long)duration;
-(BOOL)hasCoverArt;
-(id)coverArt;
-(id)coverArtID;
-(id)mediaType;
-(id)primaryCollectionTitle;
@end

