/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEAssetExpirationMonitor.h"
#import <BackRow/BRBackgroundTask.h>

@class NSDate;

@interface MEAssetExpirationMonitor : BRBackgroundTask {
	NSDate* _executionDate;
}
-(BOOL)perform:(id)perform;
@end

@interface MEAssetExpirationMonitor (Private)
-(void)_updateExecutionDateToTodayPlus:(int)todayPlus;
-(void)dealloc;
-(void)_performAssetExpirationCheck;
-(BOOL)_isExpirationDate:(id)date approachingDate:(id)date2;
-(void)_deleteAsset:(id)asset;
@end

