/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import <BackRow/BRControl.h>

@class BRWaitSpinnerControl, BRTextControl;

@interface MEDatabaseSyncDialogBoundingControl : BRControl {
	BRControl* _leftEdge;
	BRControl* _topEdge;
	BRControl* _rightEdge;
	BRControl* _bottomEdge;
	BRWaitSpinnerControl* _spinner;
	BRTextControl* _messageTextCtl;
	BRTextControl* _instructionsTextCtl;
}
-(id)init;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)layoutSubcontrols;
@end

