/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import <BackRow/BRControl.h>

@class MEDatabaseSyncDialogBoundingControl;

@interface MEDatabaseSyncDialog : BRControl {
	MEDatabaseSyncDialogBoundingControl* _boundingControl;
}
+(void)dismissDatabaseSyncDialog;
+(void)postDatabaseSyncDialog;
+(void)_postDialogWhenReady:(id)ready;
+(void)_postDialog:(id)dialog;
-(id)init;
-(CGSize)sizeThatFits:(CGSize)fits;
-(BOOL)brEventAction:(id)action;
@end

