/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRPhotoMediaCollection.h>
#import "Lowtide-Structs.h"

@class BRMediaCollectionType;

@interface MEIPhotoMediaCollection : BRPhotoMediaCollection {
	BOOL _isLocal;
	ITImageAlbum* _album;
	BRMediaCollectionType* _type;
}
+(id)collectionWithProvider:(id)provider album:(ITImageAlbum*)album;
-(id)initWithProvider:(id)provider album:(ITImageAlbum*)album;
-(void)willBeDeleted;
-(id)description;
-(id)imageProxy;
-(id)collectionID;
-(id)mediaAssets;
-(id)title;
-(id)collectionName;
-(id)collectionType;
-(BOOL)isLocal;
-(id)keyAssetID;
-(BOOL)isLibrary;
-(id)archivableCollectionInfo;
-(id)mediaTypes;
@end

