/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "MEIPhotoMediaProvider.h"

@class BRImage;

@interface MEIPhotoRemoteMediaProvider : MEIPhotoMediaProvider {
	BOOL _serverLoaded;
	BOOL _infoValid;
	BRImage* _blankImage;
}
-(void)dealloc;
-(BOOL)isLocal;
-(int)load;
-(int)unload;
-(void)photoLibraryReceived:(ITImageLibrary*)received withHTTPStatus:(unsigned long)httpstatus;
@end

