/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "MEIPhotoMediaAsset.h"
#import <BackRow/BRPhotoMediaAsset.h>


@interface MEIPhotoMediaAsset : BRPhotoMediaAsset {
	ITImageInfo* _imageInfo;
}
+(id)assetWithMediaProvider:(id)mediaProvider imageinfo:(ITImageInfo*)imageinfo;
-(id)initWithMediaProvider:(id)mediaProvider imageInfo:(ITImageInfo*)info;
-(void)willBeDeleted;
-(BOOL)isLocal;
-(id)dateTaken;
-(CGRect)faceRectForFaceCollectionID:(id)faceCollectionID;
-(id)subImageProxyWithRect:(CGRect)rect;
@end

@interface MEIPhotoMediaAsset (Private)
-(CGRect)_paddedFaceRectFromFaceRect:(CGRect)faceRect;
@end

