/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesArtist.h"
#import "Lowtide-Structs.h"
#import "MEITunesMediaCollection.h"


@interface MEITunesArtist : MEITunesMediaCollection {
}
-(void)willBeDeleted;
-(BOOL)isValid;
-(id)collectionID;
-(int)count;
-(id)mediaAssets;
-(id)artist;
-(id)artistForSorting;
-(id)title;
-(id)titleForSorting;
-(id)titleNoDefault;
-(id)titleForSortingNoDefault;
-(id)collectionType;
-(id)childCollections;
-(ArtistInfo*)artistInfo;
-(BOOL)isLocal;
@end

@interface MEITunesArtist (Private)
-(id)_initWithMediaProvider:(id)mediaProvider artistInfo:(ArtistInfo*)info;
@end

