/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "MEITunesAlbum.h"
#import "MEITunesMediaCollection.h"

@class NSNumber;

@interface MEITunesAlbum : MEITunesMediaCollection {
	unsigned _compilationDetermined : 1;
	NSNumber* _isPodcastAlbum;
}
-(void)dealloc;
-(void)willBeDeleted;
-(BOOL)isValid;
-(void)resetCachedData;
-(id)collectionID;
-(id)coverArtID;
-(int)count;
-(id)mediaAssets;
-(id)assetEnumerator;
-(long)duration;
-(BOOL)isCompilation;
-(BOOL)isSingleArtistCompilation;
-(BOOL)hasCoverArt;
-(id)coverArt;
-(id)artist;
-(id)artistForSorting;
-(id)mediaType;
-(id)title;
-(id)titleForSorting;
-(id)titleNoDefault;
-(id)titleForSortingNoDefault;
-(id)collectionType;
-(AlbumInfo*)albumInfo;
-(BOOL)isPodcastAlbum;
-(BOOL)isLocal;
-(id)date;
@end

@interface MEITunesAlbum (Private)
-(id)_initWithMediaProvider:(id)mediaProvider albumInfo:(AlbumInfo*)info;
-(id)_artistForSorting:(BOOL)sorting;
-(void)_albumHasArtwork:(id)artwork;
-(void)_coverArtID:(id)anId;
-(void)_coverArt:(id)art;
-(void)_coverArtFromContainedAssets:(id)containedAssets;
@end

