/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "MEiTunesRentalDataClient.h"

@class BRBackgroundTask, NSCountedSet, NSArray, NSMutableArray;

@interface MEiTunesRentalDataClientImpl : MEiTunesRentalDataClient {
	BRBackgroundTask* _rentalExpirationTask;
	ATVDataClientRef _dataClientRef;
	/*function-pointer*/ void* _connectCallBack;
	void* _connectInfo;
	NSArray* _rentals;
	double _lastRefreshInitiated;
	BOOL _acquisitionRefreshesRentals;
	NSMutableArray* _cacheTriggers;
	int _lastRankValue;
	NSCountedSet* _showInfosToIgnore;
	BOOL _overrideRentalCountCheck;
}
-(id)init;
-(void)dealloc;
-(void)connectClient:(ATVDataClientRef)client stateChangedFn:(/*function-pointer*/ void*)fn info:(void*)info;
-(void)disconnectClient:(ATVDataClientRef)client;
-(void)setRentals:(id)rentals;
-(id)rentals;
-(void)setDataClientRef:(ATVDataClientRef)ref;
-(void)_updateRental:(ATVMediaItemRef)rental withShowInfo:(id)showInfo transactionOptions:(id)options;
-(void)_updateShowInfoForRentals:(id)rentals;
-(id)buildRentalsArray:(id)array;
-(id)processQuery:(ATVMediaQueryRef)query;
-(ATVMediaItemRef)mediaItemWithEarliestExpirationDate;
-(void)availableRentals:(id)rentals;
-(void)availableRentalCount:(id)count;
-(void)acquisitionSuccessful:(id)successful;
-(void)authenticationSucceeded:(id)succeeded;
-(void)authenticationCancelled:(id)cancelled;
-(void)rentalRefreshRequest:(id)request;
-(void)showInfoChanged:(id)changed;
-(void)propertyUpdated:(id)updated;
-(void)queueRentalRefreshCompleteNotification:(id)notification;
-(void)refreshAvailableRentalsOverridingRentalCheckCount;
-(void)refreshAvailableRentals;
-(void)refreshAvailableRentalsImmediate;
-(void)fetchAvailableRentals;
-(void)preferredAccountRemoved:(id)removed;
-(void)preferredAccountEstablished:(id)established;
-(void)updateRentalExpirationTask;
-(void)preferredAccountAuthenticationSucceeded:(id)succeeded;
-(void)networkStateChanged:(id)changed;
-(void)mainMenuVisible:(id)visible;
-(void)checkInOutstandingRentals:(id)outstandingRentals;
@end

