/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesMediaAssetVisitor.h"
#import <BackRow/BRSingleton.h>

@class NSTimer, NSConditionLock, NSMutableDictionary;

@interface MEITunesMediaAssetVisitor : BRSingleton {
	unsigned _journalMarker;
	unsigned _flushMarker;
	NSTimer* _persistenceTimer;
	NSConditionLock* _persistenceLock;
	NSMutableDictionary* _supplementalData;
}
+(id)singleton;
+(void)setSingleton:(id)singleton;
-(id)init;
-(void)dealloc;
-(unsigned)bookmarkTimeInMS:(id)ms;
-(void)setBookmarkTimeInMS:(unsigned)ms mediaAsset:(id)asset;
-(void)incrementPerformanceCountForMediaAsset:(id)mediaAsset;
-(long)performanceCountForMediaAsset:(id)mediaAsset;
@end

@interface MEITunesMediaAssetVisitor (Private)
-(id)_supplementalDataRepositoryPath;
-(id)_supplementalDataForMediaAsset:(id)mediaAsset;
-(void)_makeSupplementalDataPersistent:(id)persistent;
-(void)_purgeDataForDataServer:(id)dataServer;
@end

