/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import <BackRow/BRBackgroundTask.h>


@interface MEiTunesRentalExpirationTask : BRBackgroundTask {
	ATVMediaItemRef _item;
}
-(id)initWithMediaItemRef:(ATVMediaItemRef)mediaItemRef;
-(void)dealloc;
-(BOOL)perform:(id)perform;
@end

