/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRBaseMediaProvider.h>

@class MEITunesLibrary;

@interface MEITunesBaseMediaProvider : BRBaseMediaProvider {
	MEITunesLibrary* _library;
}
-(id)initWithLibrary:(id)library;
-(void)dealloc;
-(id)library;
-(BOOL)autoload;
-(int)load;
-(int)unload;
-(void)flush;
-(id)providerID;
-(id)providerName;
-(id)machineID;
-(long)countOfObjectsWithMediaType:(id)mediaType;
@end

