/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "MEITunesMediaAsset.h"


@interface MEITunesPodcastSubscriptionAsset : MEITunesMediaAsset {
}
-(id)mediaType;
-(id)_mediaType:(TrackInfo*)type;
@end

