/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRDeletable.h"
#import "Lowtide-Structs.h"
#import "MEITunesPlaylist.h"
#import "MEITunesMediaCollection.h"


@interface MEITunesPlaylist : MEITunesMediaCollection <BRDeletable> {
	BOOL _isDirty;
}
-(void)willBeDeleted;
-(BOOL)isValid;
-(id)collectionID;
-(BOOL)hasCoverArt;
-(id)coverArtID;
-(id)coverArt;
-(id)collectionType;
-(Playlist*)playlist;
-(id)mediaTypes;
-(BOOL)isDirty;
-(void)setIsDirty:(BOOL)dirty;
-(int)count;
-(id)title;
-(id)titleForSorting;
-(id)titleNoDefault;
-(id)titleForSortingNoDefault;
-(id)parentCollection;
-(id)childCollections;
-(id)mediaType;
-(id)mediaAssets;
-(BOOL)isLocal;
-(BOOL)isAvailable;
-(BOOL)isHidden;
-(BOOL)canBeDeleted;
-(void)delete;
-(id)date;
@end

@interface MEITunesPlaylist (Private)
-(id)_initWithMediaProvider:(id)mediaProvider playlist:(Playlist*)playlist;
@end

