/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import <Foundation/NSEnumerator.h>

@class MEITunesAlbum;

@interface MEITunesAlbumAssetEnumerator : NSEnumerator {
	MEITunesAlbum* _album;
	TrackInfo* _trackInfo;
}
-(id)initWithAlbum:(id)album;
-(void)dealloc;
-(id)nextObject;
-(id)allObjects;
@end

