/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesRemoteMediaProvider.h"
#import "MEITunesMediaProvider.h"


@interface MEITunesRemoteMediaProvider : MEITunesMediaProvider {
}
-(BOOL)isLocal;
-(int)load;
-(void)setStatus:(int)status;
-(int)unload;
-(void)finalizeUnload;
@end

@interface MEITunesRemoteMediaProvider (Protected)
-(int)_loadLibrary:(id)library;
@end

