/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRDeletable.h"
#import "MEITunesMediaAsset.h"
#import "Lowtide-Structs.h"
#import <BackRow/BRBaseMediaAsset.h>

@class NSString;

@interface MEITunesMediaAsset : BRBaseMediaAsset <BRDeletable> {
	unsigned _objectID;
	unsigned _trackLocationPrepped : 1;
	CFDictionaryRef _infoDictionary;
	NSString* _assetID;
}
+(void)initialize;
+(id)mediaAssetFromMediaProvider:(id)mediaProvider withTrackInfo:(TrackInfo*)trackInfo;
+(id)mediaAssetWithMediaAsset:(id)mediaAsset;
-(id)initWithMediaProvider:(id)mediaProvider trackInfo:(TrackInfo*)info;
-(void)dealloc;
-(void)willBeDeleted;
-(BOOL)canBeDeleted;
-(void)delete;
-(unsigned)bookmarkTimeInMS;
-(void)setBookmarkTimeInMS:(unsigned)ms;
-(unsigned)startTimeInMS;
-(unsigned)stopTimeInMS;
-(id)assetID;
-(id)coverArtID;
-(id)artist;
-(id)artistForSorting;
-(id)title;
-(id)titleForSorting;
-(id)cast;
-(id)producers;
-(id)directors;
-(id)mediaSummary;
-(id)mediaDescription;
-(id)copyright;
-(long)duration;
-(BOOL)hasBeenPlayed;
-(void)setHasBeenPlayed:(BOOL)played;
-(long)performanceCount;
-(void)incrementPerformanceCount;
-(void)incrementPerformanceOrSkipCount:(unsigned)count;
-(id)mediaURL;
-(id)previewURL;
-(BOOL)hasCoverArt;
-(id)coverArt;
-(id)coverArtForBookmarkTimeInMS:(unsigned)ms;
-(id)dateAcquired;
-(id)dateCreated;
-(id)sourceID;
-(id)datePublished;
-(id)mediaType;
-(id)primaryGenre;
-(id)primaryGenreAsString;
-(id)genres;
-(int)primaryCollectionOrder;
-(int)physicalMediaID;
-(id)seriesName;
-(id)seriesNameForSorting;
-(id)broadcaster;
-(id)episodeNumber;
-(unsigned)season;
-(unsigned)episode;
-(id)mediaCollections;
-(float)userStarRating;
-(void)setUserStarRating:(float)rating;
-(id)rating;
-(BOOL)closedCaptioned;
-(BOOL)dolbyDigital;
-(BOOL)isWidescreen;
-(BOOL)isHD;
-(float)starRating;
-(id)publisher;
-(id)composer;
-(id)composerForSorting;
-(BOOL)hasVideoContent;
-(id)resolution;
-(BOOL)isDisabled;
-(BOOL)isProtectedContent;
-(id)playbackRightsOwner;
-(id)primaryCollection;
-(id)artistCollection;
-(id)collections;
-(PlaylistItem*)playlistItem;
-(TrackData*)trackData;
-(TrackInfo*)trackInfo;
-(id)trackInfoValue;
-(CFDictionaryRef)infoDictionary;
-(id)description;
-(id)dateAcquiredString;
-(id)datePublishedString;
-(BOOL)canBePlayedInShuffle;
-(void)logDescription;
-(BOOL)isLocal;
-(BOOL)isAvailable;
-(long)parentalControlRatingSystemID;
-(long)parentalControlRatingRank;
-(BOOL)isExplicit;
-(BOOL)isCheckedOut;
-(void)resetCachedData;
-(id)imageProxy;
-(id)imageProxyWithBookMarkTimeInMS:(unsigned)ms;
-(id)primaryCollectionTitle;
-(BOOL)isDownload;
-(id)grouping;
@end

@interface MEITunesMediaAsset (Private)
-(void)_prepareTrackLocation:(TrackInfo*)location;
-(id)_infoDictionaryCollectionForKey:(id)key;
-(id)_artistForSorting:(BOOL)sorting;
-(id)_titleForSorting:(BOOL)sorting;
-(id)_coverArtWithBookmarkTimeInMS:(unsigned)ms trackInfo:(TrackInfo*)info;
-(void)_coverArtOnMainThread:(id)thread;
-(void)_hasCoverArt:(id)art;
-(id)_assetInfoDictionary;
-(void)skip;
-(id)_mediaType:(TrackInfo*)type;
-(BOOL)_hasBeenPlayed:(TrackInfo*)played;
-(long)_performanceCount:(TrackInfo*)count;
-(BOOL)_shouldPerformanceRestart:(unsigned)restart trackInfo:(TrackInfo*)info;
-(id)_assetID:(TrackInfo*)anId;
-(BOOL)_trackInfoHasCoverArt:(TrackInfo*)art;
-(id)_seriesNameForSorting:(TrackInfo*)sorting;
-(id)_seriesName:(TrackInfo*)name;
-(id)_mediaURL:(TrackInfo*)url;
-(id)_primaryGenreAsString:(TrackInfo*)string;
-(CFDictionaryRef)_infoDictionary:(TrackInfo*)dictionary;
@end

