/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesUtilities.h"
#import <Foundation/NSObject.h>
#import "BRITunesUtilities.h"


@interface MEITunesUtilities : NSObject <BRITunesUtilities> {
}
+(void)initialize;
+(void)checkInJournaledEntries;
+(id)journalObjectForAsset:(id)asset;
+(void)removeJournalForRentalID:(unsigned long long)rentalID;
-(id)rentalGUID;
-(BOOL)attemptAuthorizationForAsset:(id)asset error:(id*)error;
-(void)deauthorizeAssetIfNecessary:(id)necessary;
-(id)iTunesCompareAscending:(BOOL)ascending withKey:(id)key;
-(int)iTunesCompareString:(id)string toString:(id)string2;
-(id)sortStringForString:(id)string;
-(id)urlSuitableForPlayback:(id)playback;
-(unsigned long)randomPlaylistIndex:(unsigned long)index;
-(id)keyBagPathForPairingGUID:(unsigned long long)pairingGUID;
@end

@interface MEITunesUtilities (Journal)
+(void)_writeJournal:(id)journal;
@end

