/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import <BackRow/BRBaseMediaCollection.h>


@interface MEITunesMediaCollection : BRBaseMediaCollection {
	unsigned _objectID;
}
+(void)initialize;
+(id)mediaCollectionFromMediaProvider:(id)mediaProvider withAlbumInfo:(AlbumInfo*)albumInfo;
+(id)mediaCollectionFromMediaProvider:(id)mediaProvider withPlaylist:(Playlist*)playlist;
+(id)mediaCollectionFromMediaProvider:(id)mediaProvider withArtistInfo:(ArtistInfo*)artistInfo;
+(void)databaseSyncFinished:(id)finished;
+(void)_updateGeniusMixArtwork;
+(id)geniusMixImageManager;
-(TrackData*)trackData;
-(void)resetCachedData;
-(void)willBeDeleted;
-(BOOL)hasCoverArt;
-(id)coverArtID;
-(id)coverArt;
-(id)imageProxy;
@end

