/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "MEITunesAssetExpiryInfo.h"
#import <BackRow/BRMediaAssetExpiryInfo.h>


@interface MEITunesAssetExpiryInfo : BRMediaAssetExpiryInfo {
}
-(id)initWithMediaAsset:(id)mediaAsset;
-(BOOL)isExpired;
-(id)expiryDate;
-(unsigned)rentalPlaybackDuration;
@end

@interface MEITunesAssetExpiryInfo (Private)
-(ATVMediaItemRef)_mediaItemRef;
@end

