/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRImageProxy.h"
#import <Foundation/NSObject.h>

@class MEITunesMediaCollection;

@interface MEITunesMediaCollectionImageProxy : NSObject <BRImageProxy> {
	MEITunesMediaCollection* _collection;
}
+(id)imageProxyWithCollection:(id)collection;
-(id)initWithCollection:(id)collection;
-(void)dealloc;
-(id)imageIDForImageSize:(int)imageSize;
-(id)imageForImageSize:(int)imageSize;
-(id)defaultImageForImageSize:(int)imageSize;
-(BOOL)supportsImageForImageSize:(int)imageSize;
-(void)cancelImageRequestsForImageSizes:(int)imageSizes;
-(id)object;
@end

