/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesStreamingMediaAsset.h"
#import "BRMediaAssetDerivesMediaURL.h"
#import <BackRow/BRStreamingMediaAsset.h>


@interface MEITunesStreamingMediaAsset : BRStreamingMediaAsset <BRMediaAssetDerivesMediaURL> {
}
-(long)parentalControlRatingSystemID;
-(long)parentalControlRatingRank;
-(BOOL)isExplicit;
-(id)rating;
-(id)trickPlayURL;
-(id)resolveMediaURL;
@end

@interface MEITunesStreamingMediaAsset (Private)
-(BOOL)_isShowInfoStoredInKeyValueStore;
@end

