/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesBaseMediaProvider.h"
#import "Lowtide-Structs.h"
#import "MEITunesMediaProvider.h"
#import "BRMediaIdentityProtocol.h"


@interface MEITunesMediaProvider : MEITunesBaseMediaProvider <BRMediaIdentityProtocol> {
}
+(void)initialize;
-(void)dealloc;
-(BOOL)isLocal;
-(id)mediaTypes;
-(id)mostRecentAlbums:(unsigned)albums;
-(id)mediaForEntityName:(id)entityName;
-(id)objectsWithEntityName:(id)entityName qualifiedByPredicate:(id)predicate sortDescriptors:(id)descriptors excludeHiddenObjects:(BOOL)objects error:(id*)error;
-(int)load;
-(int)unload;
-(int)unloadPreservingDownloads:(BOOL)downloads;
@end

@interface MEITunesMediaProvider (MEITunesMediaProviderDatabaseModification)
-(void)addTrack:(TrackInfo*)track;
-(void)deleteTrack:(TrackInfo*)track;
-(void)addAlbum:(AlbumInfo*)album;
-(void)deleteAlbum:(AlbumInfo*)album;
-(void)addPlaylist:(Playlist*)playlist;
-(void)deletePlaylist:(Playlist*)playlist;
-(void)addArtist:(ArtistInfo*)artist;
-(void)deleteArtist:(ArtistInfo*)artist;
@end

@interface MEITunesMediaProvider (Protected)
-(int)_loadLibrary:(id)library;
-(void)_loadTracks:(id)tracks;
-(void)_loadPlaylists:(id)playlists;
-(void)_loadAlbums:(id)albums;
-(void)_loadArtists:(id)artists;
-(id)_assetsFilteredByPredicate:(id)predicate;
-(id)_collectionsFilteredByPredicate:(id)predicate excludeHidden:(BOOL)hidden;
-(id)_albumsFilteredByPredicate:(id)predicate;
-(id)_playlistsFilteredByPredicate:(id)predicate excludeHidden:(BOOL)hidden;
-(id)_artistsFilteredByPredicate:(id)predicate;
-(void)_makeAssetsPerformSelector:(SEL)selector;
-(void)_makeAssetsPerformSelector:(SEL)selector predicate:(id)predicate;
-(void)_makeCollectionsPerformSelector:(SEL)selector;
@end

