/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MEITunesGeniusMixImageManager.h"
#import <Foundation/NSObject.h>

@class BRAsyncTaskContext, NSMutableArray;

@interface MEITunesGeniusMixImageManager : NSObject {
	BRAsyncTaskContext* _taskContext;
	NSMutableArray* _pendingMixArtworkInfos;
}
-(id)init;
-(void)dealloc;
-(void)updateGeniusMixArtwork;
-(id)artworkForGeniusMixWithID:(id)anId;
-(id)generatedImageForGeniusMixWithID:(id)anId;
-(void)cacheGeneratedImage:(id)image forGeniusMixWithID:(id)anId;
@end

@interface MEITunesGeniusMixImageManager (Private)
-(void)_generateArtworkForMixArtworkInfo:(id)mixArtworkInfo;
-(void)_queueScaleTaskForMixWithInfo:(id)info;
-(void)_writeImage:(id)image atPath:(id)path;
-(void)_scaleImage:(id)image;
-(void)_writeImage:(id)image;
-(void)_imageReady:(id)ready;
@end

