/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class MEITunesPlaylist, NSArray;

@interface MEITunesGeniusMixArtworkInfo : NSObject {
	MEITunesPlaylist* _mix;
	NSArray* _currentImages;
	NSArray* _pendingLoadImageIDs;
}
+(id)mixArtworkInfoForMix:(id)mix;
-(id)initWithMix:(id)mix;
-(void)dealloc;
-(id)mix;
-(id)currentImages;
-(void)setCurrentImages:(id)images;
-(id)pendingLoadImageIDs;
-(void)setPendingLoadImagedIDs:(id)ids;
-(void)updateImage:(id)image withPendingID:(id)pendingID;
-(id)artworkIDs;
-(id)mixPath;
@end

