/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"
#import "BRMusicStoreImageDecryptionAgent.h"
#import <Foundation/NSObject.h>


@interface MEMusicStoreImageDecryptionAgent : NSObject <BRMusicStoreImageDecryptionAgent> {
}
-(CFDataRef)decryptImageBuffer:(CFDataRef)buffer;
@end

