/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRControl.h>

@class MEPowerManagement;

@interface MEPowerManagementControl : BRControl {
	MEPowerManagement* _manager;
}
-(void)setManager:(id)manager;
-(BOOL)brEventAction:(id)action;
@end

