/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MESyncState.h"

@class NSNotificationCenter, BRTimer;

@interface MESyncStateSyncDB : MESyncState {
	long _itemCount;
	NSNotificationCenter* _notificationCenter;
	BRTimer* _timer;
}
-(id)initWithDescription:(id)description;
-(void)reset;
-(void)startTimer;
-(id)processSyncEvent:(id)event forItem:(id)item;
-(long)transactionThreshold;
@end

