/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface MESyncEvent : NSObject {
	NSString* _description;
}
+(id)databaseSyncStarted;
+(id)databaseSyncComplete;
+(id)databaseReloadStarted;
+(id)databaseReloadComplete;
+(id)itemAdded;
+(id)itemModified;
+(id)itemDeleted;
-(id)initWithDescription:(id)description;
-(void)dealloc;
-(id)description;
@end

