/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface MESyncState : NSObject {
	NSString* _description;
}
+(void)initialize;
+(id)syncState;
+(id)processSyncEvent:(id)event forItem:(id)item;
+(id)idle;
+(id)syncingDatabase;
-(id)initWithDescription:(id)description;
-(void)dealloc;
-(id)processSyncEvent:(id)event forItem:(id)item;
-(id)description;
-(id)typeOfItem:(id)item;
@end

