/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ATVITunesTouchRemoteManager.h"
#import "METouchRemoteManager.h"
#import <BackRow/BRSingleton.h>

@class NSTimer;

@interface METouchRemoteManager : BRSingleton <ATVITunesTouchRemoteManager> {
	NSTimer* _updateTimer;
}
+(void)setSingleton:(id)singleton;
+(id)singleton;
-(id)init;
-(void)dealloc;
-(id)pairedTouchRemotes;
-(id)pairableTouchRemotes;
-(BOOL)removePairedTouchRemote:(id)remote;
-(void)pairWithTouchRemote:(id)touchRemote withPIN:(id)pin;
-(unsigned long)sendGeneralPurposeMessage:(id)message;
@end

@interface METouchRemoteManager (Artwork)
-(void)_scaleImage:(id)image;
-(void)_updateNowPlayingArtworkWithInfo:(id)info;
@end

@interface METouchRemoteManager (Updates)
-(void)_clearUpdateTimer;
-(void)_updateTouchRemotes;
-(void)_updateTouchRemotesWithDelay:(double)delay;
-(void)_updateTimerFired:(id)fired;
@end

@interface METouchRemoteManager (Notifications)
-(void)_nowPlayingUpdated:(id)updated;
-(void)_coverArtChanged:(id)changed;
-(void)_playerTimeSkipped:(id)skipped;
-(void)_playerVolumeChanged:(id)changed;
@end

