/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <BackRow/BRSingleton.h>
#import "METouchRemoteDecryptionAgent.h"

@class NSData;

@interface METouchRemoteDecryptionAgent : BRSingleton {
	NSData* _certData;
	NSData* _challenge;
}
+(id)singleton;
+(void)setSingleton:(id)singleton;
-(id)init;
-(void)dealloc;
-(id)decryptMessage:(id)message;
-(id)certificateString;
-(id)challengeString;
@end

@interface METouchRemoteDecryptionAgent (Private)
-(id)_decryptStringFromData:(id)data;
-(id)_convertStringToData:(id)data;
-(id)_convertDataToString:(id)string;
-(BOOL)_sendCertToTouchDevices;
-(id)_updateChallenge;
-(BOOL)_sendNewChallengeToTouchDevices;
@end

