/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Lowtide-Structs.h"


@protocol MPAssetKeyDelegate
-(id)absolutePathForAssetKey:(id)assetKey;
-(id)absolutePathForAssetKey:(id)assetKey andSize:(CGSize)size;
-(id)absolutePathForStillAssetAtPath:(id)path andSize:(CGSize)size;
@optional
-(id)mapTileCenteredAt:(id)at size:(CGSize)size inset:(CGSize)inset;
-(id)mapTileForPath:(id)path;
-(id)flightPlanFrom:(CGPoint)from to:(CGPoint)to;
-(CGSize)resolutionForAssetKey:(id)assetKey;
-(id)relativePathForAssetWithAttributes:(id)attributes;
-(id)relativeTiledPathsForAssetWithAttributes:(id)attributes;
-(id)attributeForKey:(id)key forAssetKey:(id)assetKey withOptions:(id)options;
-(CGImageRef)retainedCGImageForAssetKey:(id)assetKey andSize:(CGSize)size;
-(IOSurfaceRef)retainedIOSurfaceForAssetKey:(id)assetKey andSize:(CGSize)size;
-(CGImageRef)cgImageForAssetKey:(id)assetKey andSize:(CGSize)size;
@end

