/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSString.h>


@interface NSString (iTunesAdditions)
+(id)stringWithUStr255:(unsigned short [256])ustr255;
-(int)iTunesCompare:(id)compare;
@end

