GO_EASY_ON_ME=1
FW_DEVICE_IP=apple-tv.local
export SDKVERSION=4.2
TOOL_NAME := defaults
defaults_FILES = defaults.m
defaults_PACKAGE_TARGET_DIR = /usr/bin
defaults_LDFLAGS = -framework Foundation #-framework BackRow

include theos/makefiles/common.mk
include theos/makefiles/tool.mk
